inverter:
  address: "sungrow:502"

metrics:
  - name: device_info
    help: "Device Info (constant value)"
    type: gauge
    value:
      fromExpression: 1
    labels:
      - name: model
        value:
          fromRegister:
            type: u16
            address: 5000
            mapValue:
              0xe00: SH5.0RT
              0xe01: SH6.0RT
              0xe02: SH8.0RT
              0xe03: SH10RT
      - name: sn
        value:
          fromRegister:
            type: string
            address: 4990
            length: 10
      - name: arm_sw_ver
        value:
          fromRegister:
            type: string
            address: 4954
            length: 15
      - name: dsp_sw_ver
        value:
          fromRegister:
            type: string
            address: 4969
            length: 15
      - name: protocol_no
        value:
          fromRegister:
            type: u32
            address: 4950
      - name: protocol_ver
        value:
          fromRegister:
            type: u32
            address: 4952
      - name: nominal_output_power_watts
        value:
          fromRegister:
            type: u16
            address: 5001
            mapValue:
              x: 100*x
      - name: output_type
        value:
          fromRegister:
            type: u16
            address: 5002
            mapValue:
              0: single
              1: 3P4L
              2: 3P3L

  - name: output_energy_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 5003
        mapValue:
          x: 100*x

  - name: output_energy_total_watthours
    alias: sunspec_WattHours_WH_Wh
    type: counter
    value:
      fromRegister:
        type: u32
        address: 5004
        mapValue:
          x: 100*x

  - name: pv_yield_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13002
        mapValue:
          x: 100*x

  - name: pv_yield_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13003
        mapValue:
          x: 100*x

  - name: export_energy_from_pv_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13005
        mapValue:
          x: 100*x

  - name: export_energy_from_pv_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13006
        mapValue:
          x: 100*x

  - name: import_energy_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13036
        mapValue:
          x: 100*x

  - name: import_energy_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13037
        mapValue:
          x: 100*x

  - name: export_energy_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13045
        mapValue:
          x: 100*x

  - name: export_energy_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13046
        mapValue:
          x: 100*x

  - name: battery_charge_energy_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13012
        mapValue:
          x: 100*x

  - name: battery_charge_energy_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13013
        mapValue:
          x: 100*x

  - name: charge_energy_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13040
        mapValue:
          x: 100*x

  - name: charge_energy_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13041
        mapValue:
          x: 100*x

  - name: direct_energy_consumption_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13017
        mapValue:
          x: 100*x

  - name: direct_energy_consumption_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13018
        mapValue:
          x: 100*x

  - name: battery_discharge_energy_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 13026
        mapValue:
          x: 100*x

  - name: battery_discharge_energy_total_watthours
    type: counter
    value:
      fromRegister:
        type: u32
        address: 13027
        mapValue:
          x: 100*x

  - name: cabinet_temperature_celsius
    type: gauge
    alias: sunspec_Cabinet_Temperature_TmpCab_C
    value:
      fromRegister:
        type: s16
        address: 5008
        mapValue:
          x: x/10

  - name: mppt1_voltage_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5011
        mapValue:
          x: x/10
  - name: mppt1_current_amperes
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5012
        mapValue:
          x: x/10
  - name: mppt2_voltage_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5013
        mapValue:
          x: x/10
  - name: mppt2_current_amperes
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5014
        mapValue:
          x: x/10

  - name: dc_power_total_watts
    alias: sunspec_DC_Watts_DCW_W
    type: gauge
    value:
      fromRegister:
        type: u32
        address: 5017

  - name: phase_voltage_a_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5019
        mapValue:
          x: x/10
  - name: phase_voltage_b_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5020
        mapValue:
          x: x/10
  - name: phase_voltage_c_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5021
        mapValue:
          x: x/10

  - name: phase_current_a_amperes
    type: gauge
    value:
      fromRegister:
        type: s16
        address: 13031
        mapValue:
          x: x/10
  - name: phase_current_b_amperes
    type: gauge
    value:
      fromRegister:
        type: s16
        address: 13032
        mapValue:
          x: x/10
  - name: phase_current_c_amperes
    type: gauge
    value:
      fromRegister:
        type: s16
        address: 13033
        mapValue:
          x: x/10

  - name: reactive_power_vars
    type: gauge
    value:
      fromRegister:
        type: s32
        address: 5033

  - name: power_factor
    type: gauge
    value:
      fromRegister:
        type: s16
        address: 5035
        mapValue:
          x: x/1000

  - name: grid_frequency_hertzs
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5036
        mapValue:
          x: x/10

  - name: export_limit_watts
    type: gauge
    value:
      fromExpression: 1
    labels:
      - name: min
        value:
          fromRegister:
            type: u16
            address: 5622
            mapValue:
              x: 10*x
      - name: max
        value:
          fromRegister:
            type: u16
            address: 5623
            mapValue:
              x: 10*x
  - name: bdc_rated_power_watts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5628
        mapValue:
          x: 100*x

  - name: bms_max_charging_current_amperes
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5635
  - name: bms_max_discharging_current_amperes
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5636

  - name: pv_power_today_watts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6100
        length: 96
  - name: direct_power_consumption_today_watts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6290
        length: 96
  - name: export_power_from_pv_today_watts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6469
        length: 96
  - name: battery_charge_power_today_watts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6648
        length: 96

  - name: pv_yields_daily_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6196
        length: 31
        mapValue:
          x: x/10
  - name: pv_yields_monthly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6227
        length: 12
        mapValue:
          x: x/10
  - name: pv_yields_yearly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u32
        address: 6250
        length: 20
        mapValue:
          x: "x == 4294967295 ? 0 : x/10"

  - name: direct_energy_consumption_daily_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6386
        length: 31
        mapValue:
          x: x/10
  - name: direct_energy_consumption_monthly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6417
        length: 12
        mapValue:
          x: x/10
  - name: direct_energy_consumption_yearly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u32
        address: 6429
        length: 20
        mapValue:
          x: "x == 4294967295 ? 0 : x/10"

  - name: export_energy_from_pv_daily_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6565
        length: 31
        mapValue:
          x: x/10
  - name: export_energy_from_pv_monthly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6596
        length: 12
        mapValue:
          x: x/10
  - name: export_energy_from_pv_yearly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u32
        address: 6608
        length: 20
        mapValue:
          x: "x == 4294967295 ? 0 : x/10"

  - name: battery_charge_energy_daily_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6744
        length: 31
        mapValue:
          x: x/10
  - name: battery_charge_energy_monthly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6775
        length: 12
        mapValue:
          x: x/10
  - name: battery_charge_energy_yearly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u32
        address: 6787
        length: 20
        mapValue:
          x: "x == 4294967295 ? 0 : x/10"

  - name: system_state
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13000
  - name: running_state
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13001
  - name: grid_state
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13030

  - name: load_power_watts
    type: gauge
    value:
      fromRegister:
        type: s32
        address: 13008
  - name: export_power_watts
    type: gauge
    value:
      fromRegister:
        type: s32
        address: 13010
  - name: total_active_power_watts
    type: gauge
    value:
      fromRegister:
        type: s32
        address: 13034
  - name: self_consumption_ratio
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13029
        mapValue:
          x: x/1000

  - name: battery_voltage_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13020
        mapValue:
          x: x/10
  - name: battery_current_amperes
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13021
        mapValue:
          x: x/10
  - name: battery_power_watts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13022
        mapValue:
          x: x/10
  - name: battery_level_percents
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 13023
        mapValue:
          x: x/10
  - name: battery_temperature_celsius
    type: gauge
    value:
      fromRegister:
        type: s16
        address: 13025
        mapValue:
          x: x/10