inverter:
  address: "sungrow:502"

metrics:
  - name: device_info
    help: "Device Info (constant value)"
    type: gauge
    value:
      fromExpression: 1
    labels:
      - name: type
        value:
          fromRegister:
            type: u16
            address: 5000
            mapValue:
              0xe00: SH5.0RT
              0xe03: SH10RT
      - name: sn
        value:
          fromRegister:
            type: string
            address: 4990
            length: 10
      - name: arm_sw_ver
        value:
          fromRegister:
            type: string
            address: 4954
            length: 15
      - name: dsp_sw_ver
        value:
          fromRegister:
            type: string
            address: 4969
            length: 15

  - name: output_energy_daily_watthours
    type: counter
    value:
      fromRegister:
        type: u16
        address: 5003
        mapValue:
          x: 100*x

  - name: output_energy_total_watthours
    alias: sunspec_WattHours_WH_Wh
    type: counter
    value:
      fromRegister:
        type: u32
        address: 5004
        mapValue:
          x: 100*x

  - name: cabinet_temperature_celsius
    type: gauge
    alias: sunspec_Cabinet_Temperature_TmpCab_C
    value:
      fromRegister:
        type: s16
        address: 5008
        mapValue:
          x: x/10

  - name: mppt1_voltage_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5011
        mapValue:
          x: x/10
  - name: mppt1_current_amperes
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5012
        mapValue:
          x: x/10
  - name: mppt2_voltage_volts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5013
        mapValue:
          x: x/10
  - name: mppt2_current_amperes
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5014
        mapValue:
          x: x/10

  - name: reactive_power_vars
    type: gauge
    value:
      fromRegister:
        type: s32
        address: 5033

  - name: power_factor
    type: gauge
    value:
      fromRegister:
        type: s16
        address: 5035
        mapValue:
          x: x/1000

  - name: grid_frequency_hertzs
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 5036
        mapValue:
          x: x/10

  - name: pv_power_today_watts
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6100
        length: 96
  - name: pv_yields_daily_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6196
        length: 31
        mapValue:
          x: x/10
  - name: pv_yields_monthly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u16
        address: 6227
        length: 12
        mapValue:
          x: x/10
  - name: pv_yields_yearly_kilowatthours
    type: gauge
    value:
      fromRegister:
        type: u32
        address: 6250
        length: 20
        mapValue:
          x: "x == 4294967295 ? 0 : x/10"

