- name: clock
  registers:
    W001_system_clock_year:
      x: "timeParse(x, '2006-01-02 15:04:05 MST', 'Europe/Berlin').Year()"
    W002_system_clock_month:
      x: "timeParse(x, '2006-01-02 15:04:05 MST', 'Europe/Berlin').Month()"
    W003_system_clock_day:
      x: "timeParse(x, '2006-01-02 15:04:05 MST', 'Europe/Berlin').Day()"
    W004_system_clock_hour:
      x: "timeParse(x, '2006-01-02 15:04:05 MST', 'Europe/Berlin').Hour()"
    W005_system_clock_minute:
      x: "timeParse(x, '2006-01-02 15:04:05 MST', 'Europe/Berlin').Minute()"
    W006_system_clock_second:
      x: "timeParse(x, '2006-01-02 15:04:05 MST', 'Europe/Berlin').Second()"
  valueFromExpression: >-
    timeDate(
      register('W001_system_clock_year'), 
      register('W002_system_clock_month'),
      register('W003_system_clock_day'),
      register('W004_system_clock_hour'), 
      register('W005_system_clock_minute'),
      register('W006_system_clock_second'),
      'Europe/Berlin'
    ).Format('2006-01-02 15:04:05 MST')

- name: start_stop
  registers:
    W008_start_stop: ~

- name: max_state_of_charge
  registers:
    W033_max_soc: ~

- name: min_state_of_charge
  registers:
    W034_min_soc: ~

- name: export_power_limit
  registers:
    W049_export_power_limitation: ~

- name: export_power_limit_state
  registers:
    W058_export_power_limitation: ~

- name: charge_discharge_power
  registers:
    W028_charge_discharge_power: ~

- name: off_grid_option
  registers:
    W050_off_grid_option: ~

- name: reserved_backup_stage_of_charge
  registers:
    W050_off_grid_option: ~