name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish --bare ./src